sudo: required
services:
    - docker

before_install:
    - docker build -t tomaszmzyk/docker-react -f Dockerfile.dev .
script:
    - docker run tomaszmzyk/docker-react npm run test -- --coverage
deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker-react"
    env: "docker-react-en"
    bucket_name: "elasticbeanstalk-eu-west-1-431051797372"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: 
        secure: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
